apiVersion: v1
kind: Service
metadata:
  name: backendtest-service
spec:
  selector:
    app: backendtest
  ports:
  - protocol: "TCP"
    port: 9000
    targetPort: 9000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendtest
spec:
  selector:
    matchLabels:
      app: backendtest
  replicas: 5
  template:
    metadata:
      labels:
        app: backendtest
    spec:
      containers:
      - name: backendtest
        image: backendtest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
