# Frontend deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dpl
  namespace: production
  labels:
     app: frontend
spec:
  replicas: 1
  selector:
     matchLabels:
       app: frontend
  template:
     metadata:
       labels:
         app: frontend
     spec:
       containers:
       - name: frontend
         image: "alexspedan/netologyfrontend:latest"
         ports:
         - containerPort: 80
         env:
           - name: BASE_URL
             value: http://backend:9000

# Frontend service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-srv
  namespace: production
spec:
  selector:
     app: frontend
  ports:
     - name: web
       protocol: TCP
       port: 8000
       targetPort: 80
---
# Backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "alexspedan/netologybackend:latest"
          ports:
          - containerPort: 9000
            protocol: TCP
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@db:5432/news
---
# Backend service
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
# Statefulset DB 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: production
  name: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
        
          - name: POSTGRES_USER
            value: postgres
        
          - name: POSTGRES_DB
            value: news
---
# Source: netology1/templates/services/statefulset.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432