apiVersion: v1
kind: Service
metadata:
  name: cv-service
spec:
  selector:
    app: cv
  ports:
  - nodePort: 30163
    port: 30163
    targetPort: 80
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv
spec:
  selector:
    matchLabels:
      app: cv
  replicas: 1
  template:
    metadata:
      labels:
        app: cv
    spec:
      containers:
      - name: cv
        image: alexspedan/cv-project:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80