---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-back-pvc
  namespace: production
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi