---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend&backend
  namespace: staging
  labels:
    app: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local
  template:
    metadata:
      labels:
        app: local
    spec:
      containers:
      - name: frontend
        image: "alexspedan/netologyfrontend:latest"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /static
          name: local
      - name: backend
        image: "alexspedan/netologyfrontend:latest"
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /static
          name: local

      volumes:
      - name: local
        emptyDir: {}